version: 2

models:
  - name: dim_comics
    description: Comics dimension containing comic content and metadata
    columns:
      - name: id
        description: Comic ID from num 
        tests:
          - unique
          - not_null
      - name: title
        description: Comic title
        tests:
          - not_null
      - name: safe_title
        description: safe_title
      - name: transcript
        description: transcript
      - name: alt_text
        description: Alt text for accessibility
      - name: img_url
        description: image url
      - name: news_text
        description: News or additional information

  - name: dim_date
    description: Date dimension table with unique dates from comics
    columns:
      - name: date_key
        description: Unique date identifier in YYYYMMDD format
        tests:
          - unique
          - not_null
      - name: year
        description: Year (YYYY)
        tests:
          - not_null
      - name: month
        description: Month (1-12)
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: day
        description: Day of month (1-31)
        tests:
          - not_null

  - name: fact_metrics
    description: Fact table containing comic metrics with foreign keys to dimensions
    columns:
      - name: id
        description: auto incrementing unique identifier
        tests:
          - unique
          - not_null
      - name: comic_key
        description: Foreign key to dim_comics.id (from raw_comics.num)
        tests:
          - not_null
          - relationships:
              to: ref('dim_comics')
              field: id
      - name: date_key
        description: Foreign key to dim_date.date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: views
        description: Number of views (0-10000)
        tests:
          - not_null
      - name: customer_reviews
        description: Customer review score (1.0-10.0)
        tests:
          - not_null
      - name: cost
        description: Cost in euros (5 euros per letter in title)
        tests:
          - not_null